image: Visual Studio 2017

environment:
  MyGetApiKey:
    secure: KY/jquT/UjpGiG7tO6XSuGtlpvXYujJ4D9F19o0q+YRzuWkEBXPtyic8lhxoexTE
  SignClientSecret:
    secure: g0OJ9dO4ocXS06UgDZ1Bnd3F0JSHMo9I41z2Zc07CKk=
  SignClientUser:
    secure: uyweGSwxexnLy4dBNleW8tYcXTA291faj34PQV0ePxOTFSa5Cvf50jyICVP9mLGS
    
clone_script:
- ps: >-
    if (-not $env:appveyor_pull_request_number) {
        git clone -q --branch=$env:appveyor_repo_branch https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
        git checkout -qf $env:appveyor_repo_commit
    } else {
        git clone -q https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
        git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
        git checkout -qf FETCH_HEAD
    }
    git submodule update --init --recursive --quiet

branches:
  only:
  - master
  - v2

skip_branch_with_pr: true

skip_tags: true

skip_commits:
  files:
  - BUILDING.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - license.txt
  - README.md
  - tools/xUnitSummary.xsl

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\build.ps1 -target appveyor -buildAssemblyVersion ($env:BuildVersion + $env:APPVEYOR_BUILD_NUMBER) -buildSemanticVersion ($env:BuildSemanticVersion + $env:APPVEYOR_BUILD_NUMBER)
  
test: off

deploy: off

artifacts:
- path: artifacts/packages
- path: artifacts/test

notifications:
- provider: Slack
  incoming_webhook:
    secure: k1oXe/zscPP/vX2kQXYNO1SkIMvN47r8BNA6gkM6z5+I8rKJD+g8C3+pbdARRuzUHAMO5vzD7TXeL6fMt5oIw0QBnuAGNBLx4EsBWllmPyw=
  channel: '#pulse'
  on_build_success: true
  on_build_failure: true
