name: "xUnit.net PR Build (main)"
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - name: Clone source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        if: matrix.os == 'windows-latest'

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Get .NET information
        run: dotnet --info
        continue-on-error: true

      - name: Install Mono (Ubuntu)
        run: >
          sudo apt-get -y install apt-transport-https dirmngr gnupg ca-certificates software-properties-common &&
          curl 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3fa7e0328081bff6a14da29aa6a19b38d3d831ef' | sudo tee /etc/apt/trusted.gpg.d/mono-official-stable.asc &&
          sudo apt-add-repository -y --no-update 'deb https://download.mono-project.com/repo/ubuntu stable-focal main' &&
          sudo apt-get update &&
          sudo apt-get -y install mono-complete mono-vbnc
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Install Mono (macOS)
        run: brew install mono
        if: ${{ matrix.os == 'macOS-latest' }}

      - name: Get Mono information
        run: mono --version
        if: ${{ matrix.os != 'windows-latest' }}

      - name: "Build target: BuildAll"
        run: dotnet run --project tools/builder --no-launch-profile -- BuildAll --timing --no-x86

      - name: "Upload artifact: test-${{ matrix.os }}"
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.os }}
          path: artifacts/test
          compression-level: 9
        if: always()

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './artifacts/test/*.ctrf'
          github-report: true
          pull-request: true
          update-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
