name: "xUnit.net PR Build (main)"
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04, macOS-14]
    steps:
      - name: Clone source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Add MSBuild to PATH (Windows)
        uses: microsoft/setup-msbuild@v2
        if: matrix.os == 'windows-2022'

      - name: Replace global.json
        run: cp .github/workflows/.global.json global.json
        shell: bash

      - name: Install .NET SDK (Windows)
        run: |
          & "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --channel 8.0'
          & "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --channel 6.0 --runtime dotnet'
          & "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --architecture x86 --channel 8.0'
          & "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --architecture x86 --channel 6.0 --runtime dotnet'
        if: matrix.os == 'windows-2022'

      - name: Install .NET SDK (non-Windows)
        run: |
          ./.github/workflows/dotnet-install --channel 8.0
          ./.github/workflows/dotnet-install --channel 6.0 --runtime dotnet
          echo "$HOME/.dotnet" >> $GITHUB_PATH
        if: matrix.os != 'windows-2022'

      - name: Get .NET information
        run: dotnet --info

      - name: Get Mono information
        run: mono --version
        if: ${{ matrix.os != 'windows-2022' }}

      - name: "Build target: BuildAll"
        run: dotnet run --project tools/builder --no-launch-profile -- BuildAll --timing

      - name: "Upload artifact: test-${{ matrix.os }}"
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.os }}
          path: artifacts/test
          compression-level: 9
        if: always()
